services:
  chat-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base  
    volumes:
      - ./src:/app/src  
      - ./requirements.txt:/app/requirements.txt:ro
    environment:
      - PYTHONUNBUFFERED=1
      - RELOAD=true
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]